apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    component: payment
spec:
  containers:
    - name: frontend
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/payment:2.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    component: payment 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
