apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    component: shipping
spec:
  containers:
    - name: frontend
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/shipping:2.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    component: shipping 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080